### ISSUE TITLE
Annotation link not clickable

### ISSUE THREAD

**Issue by ravimalani86** [dearhive/dearflip-jquery-flipbook#41]
Hi 

The annotation links in the pdf are not clickable while the flipbook is open.
Also, I checked into the online demo of your website. The clickables don't work.
https://dearflip.com/examples/jquery/demo-open-file.html

I share my pdf. can you please look out for this?
https://markettime-my.sharepoint.com/:b:/p/ravi/EZcOZHVNpNpKqzHAnCaZjBcB2ViPHM_RvWtuDjCit3_IZA?e=ZDcjRP

Thank You.

**Comment by ravimalani86** [comment]
Is there any update on the above issue?

**Comment by deepak-ghimire** [comment]
Hi,

This lite repo is an old release similar to the example link. Just for users to get an idea of what the flipbook will look like.
The bugs are not fixed in this lite repo. 

Newer versions have the support:
https://dearflip.com/pdf-viewer/
Try using it without the WebGL mode.

Or our other plugin also has the support.
https://dearpdf.com/#test-demo

This lite repo will be updated once we have upgraded to ES6 standard and have proper deployment methods.
